# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /python-docker

COPY dependancies/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY src .

COPY ./scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./scripts/run.sh /run.sh
RUN chmod +x /run.sh

ENV PYTHONPATH=/app

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/run.sh"]
